spring:
  application:
    name: claim_service
  devtools:
    restart:
      trigger-file: .reloadtrigger
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis
    redis:
      time-to-live: 600000

management:
  endpoints:
    web:
      exposure:
        include: caches

server:
  port: 8081
